spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${NETZGRAFIKEDITOR_KEYCLOAK_URL}
  jooq:
    sql-dialect: Postgres
  flyway:
    enabled: true
    fail-on-missing-locations: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${NETZGRAFIKEDITOR_DB_USER}
    password: ${NETZGRAFIKEDITOR_DB_PASSWORD}
    url: ${NETZGRAFIKEDITOR_DB_URL}


endpoints:
  web:
    cors:
      path-mappings: /**
      allowed-origins: ${NETZGRAFIKEDITOR_URL}
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: "*"

logging:
  level:
    org.springframework: TRACE

auth:
  audience:
    service-name: netzgrafikeditor
