apiVersion: v1
kind: ConfigMap
metadata:
  name: chainpem-config
  labels:
    {{- include "netzgrafik-editor-backend.labels" . | nindent 4 }}
data:
  chain.pem: |
    {{ .Values.CHAIN_PEM | nindent 4 | trim }}
