apiVersion: v1
kind: ConfigMap
metadata:
  name: flatland-cloud-header
  labels:
    {{- include "netzgrafik-editor-frontend.labels" . | nindent 4 }}
    # edit to force update of configmap after editing the file:
    v: "2"
data:
  header.txt: |
   {{ .Files.Get "configs/header.txt" | nindent 4  }}