apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-additional-entrypoint
  labels:
    {{- include "netzgrafik-editor-frontend.labels" . | nindent 4 }}
    # edit to force update of configmap after editing the file:
    v: "3"
data:
  frontend-additional-entrypoint.sh: |
   {{ .Files.Get "configs/frontend-additional-entrypoint.sh" | nindent 4 | replace "BACKEND_URL" .Values.BACKEND_URL | replace "KEYCLOAK_URL" .Values.KEYCLOAK_URL | replace "PRODUCTION" .Values.PRODUCTION | replace "LABEL" .Values.LABEL  }}