apiVersion: v1
kind: Secret
metadata:
  name: tls
  labels:
    {{- include "netzgrafik-editor-frontend.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: >-
    {{ .Values.TLS_CRT }}
  tls.key: >-
    {{ .Values.TLS_KEY }}